In [1]:
import pandas as pd
pd.__version__

'2.2.1'

In [2]:
df = pd.read_csv('laptops.csv')
print(f'Records num = {df.shape[0]}')

Records num = 2160


In [3]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [4]:
df['Brand'].nunique()

27

In [5]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [6]:
df.describe().T

count         mean         std     min       25%       50%  \
RAM          2160.0    15.413889    9.867815    4.00    8.0000    16.000   
Storage      2160.0   596.294444  361.220506    0.00  256.0000   512.000   
Screen       2156.0    15.168112    1.203329   10.10   14.0000    15.600   
Final Price  2160.0  1312.638509  911.475417  201.05  661.0825  1031.945   

                 75%      max  
RAM            16.00   128.00  
Storage      1000.00  4000.00  
Screen         15.60    18.00  
Final Price  1708.97  7150.47

In [7]:
df['Screen'].median()

15.6

In [8]:
df['Screen'].mode()[0]

15.6

In [9]:
df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)

C:\Users\Angry Nerd\AppData\Local\Temp\ipykernel_14444\913004717.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)


In [10]:
df['Screen'].isnull().sum()

0

In [11]:
df['Screen'].median()

15.6

In [12]:
df['Brand'].unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [13]:
df_dell = df[df['Brand']=='Dell']
df_dell.describe()

RAM      Storage     Screen  Final Price
count  84.000000    84.000000  84.000000    84.000000
mean   11.380952   395.142857  14.686905  1153.839881
std     4.583640   175.543846   1.023669   671.795071
min     4.000000   128.000000  13.000000   379.000000
25%     8.000000   256.000000  14.000000   699.000000
50%     8.000000   256.000000  14.500000  1003.000000
75%    16.000000   512.000000  15.600000  1313.810000
max    32.000000  1000.000000  17.000000  3936.000000

In [17]:
df_injoo = df[df['Brand']=='Innjoo']
df_injoo.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [18]:
df_injoo = df_injoo[['RAM','Storage','Screen']]

In [19]:
X = df_injoo.values

In [20]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [21]:
import numpy as np

In [22]:
XTX = np.dot(X.T, X)

In [23]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [24]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [25]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [26]:
XTX_inv.shape

(3, 3)

In [27]:
X.T.shape

(3, 6)

In [28]:
res = np.dot(XTX_inv,X.T)

In [29]:
res

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [30]:
print(res.shape)
print(y.shape)

(3, 6)
(6,)


In [31]:
w = np.dot(res,y)

In [32]:
np.sum(w)

91.29988062995588